# Generated by Django 4.2 on 2024-02-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='ciutat',
        ),
        migrations.RemoveField(
            model_name='equip',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='edat',
        ),
        migrations.RemoveField(
            model_name='lliga',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='lliga',
            name='temporada',
        ),
    ]
