# Generated by Django 4.2 on 2024-03-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliga', '0003_partit_detalls_partit_inici_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='edat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
